# Generated by Django 4.0 on 2022-04-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Payment Details', 'verbose_name_plural': 'Payment Details'},
        ),
    ]
